name: firebase_management
description: Tools for managing firebase projects
version: 0.0.5
homepage: https://github.com/appsup-dart/firebase_management
repository: https://github.com/appsup-dart/firebase_management

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  snapshot: ^0.2.5
  firebase_admin: ^0.3.0
  http: '>=0.13.4 <2.0.0'
  plist_parser: '>=0.0.9 <0.3.0'
  retry: ^3.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.16.0
  melos: ^7.0.0

melos:
  useRootAsPackage: true

  ide:
    intellij: false

  command:
    version:
      includeScopes: true
      linkToCommits: true
      workspaceChangelog: false

  scripts:
    preversion: 
      exec: dart test -j 1